### PR TITLE
Fixed parsing Elite skills with level 0

### PR DESCRIPTION
**Pull request by jsnells1**

### CODE REVIEW

**Comment by michaelbull** [comment]
Was the change to the group intentional? I don't intend to change the artifact coordinate. Looks good otherwise.

**Comment by jsnells1** [comment]
Oh sorry, I'm new to Github, I didn't know it added the commits I made after the pull. I changed the group to test something until you merged the pull. Is there an easy way to revert that commit?

**Comment by jsnells1** [comment]
Nevermind, I fixed it.

**Comment by michaelbull** [comment]
Thanks! Merged. I can make a release tonight, but if you're in a hurry you can use the pre-release version from [Jitpack](https://jitpack.io/#michaelbull/rs-api/master-1.1.0-g47499c6-1).

**Pull request merged**
